-- =============================================================================
-- Quote Automation: database schema for the public demo
-- =============================================================================
-- HOW TO APPLY
--   Option A (Supabase dashboard): SQL Editor -> paste this whole file -> Run.
--   Option B (psql):  psql "$SUPABASE_DB_URL" -v ON_ERROR_STOP=1 -f supabase/schema.sql
--   Then run supabase/seed.sql the same way.
--
-- REQUIRED API SETTING (the app cannot read anything until this is done)
--   Dashboard -> Project Settings -> API (Data API) -> "Exposed schemas":
--   add  analytics, data_staging, reference, app_quote  (keep public). Save.
--
-- WHAT THIS FILE CREATES
--   app_quote.*       working tables the app reads and writes (8 tables + 1 RPC)
--   reference.*       the quote directory (who receives each quote)
--   data_staging.*    two stub tables that only carry a "last refreshed" time
--   demo.*            flat base tables that stand in for the upstream pipeline
--   analytics.*       the read model (5 views) built over demo.* + app_quote.*
--
-- In the internal version the analytics objects are materialized views fed by a
-- data pipeline. Here they are plain views over two flat demo tables, keeping
-- the same names and columns so the application code is unchanged.
--
-- SECURITY POSTURE
--   Every server-side call uses the service-role key. RLS is enabled on every
--   table with NO policies, and no schema is granted to anon/authenticated, so
--   the browser (anon key) can read nothing. The only browser-side Supabase
--   feature used is a Realtime Presence channel, which needs no table.
--
-- The file is idempotent: it can be re-run safely. Views are dropped and
-- recreated; tables use CREATE TABLE IF NOT EXISTS and keep their data.
-- =============================================================================

create schema if not exists analytics;
create schema if not exists data_staging;
create schema if not exists reference;
create schema if not exists app_quote;
create schema if not exists demo;

-- -----------------------------------------------------------------------------
-- reference.ref_quote_directory: (gc, carrier, market, project) -> recipients
-- -----------------------------------------------------------------------------
create table if not exists reference.ref_quote_directory (
  id         bigint generated by default as identity primary key,
  gc         text,
  carrier    text,
  market     text,
  project    text,
  recipient  text,          -- comma-separated To addresses
  cc         text,          -- comma-separated Cc addresses
  textjoin   text,          -- "gc_carrier_market_project" (display aid)
  -- Normalised join key, written by the app (lib/quotes/actions.ts normPart):
  -- trim, collapse whitespace, upper-case, joined with "|".
  match_key  text
);
create index if not exists ref_quote_directory_match_key_idx
  on reference.ref_quote_directory (match_key);

-- -----------------------------------------------------------------------------
-- data_staging stubs: the app reads max(loaded_at) for the "last refreshed" label
-- -----------------------------------------------------------------------------
create table if not exists data_staging.stg_invoicing_form (
  id        bigint generated by default as identity primary key,
  loaded_at timestamptz not null default now()
);
create table if not exists data_staging.stg_asset_tasks (
  id        bigint generated by default as identity primary key,
  loaded_at timestamptz not null default now()
);

-- -----------------------------------------------------------------------------
-- demo base tables (stand-ins for the upstream pipeline output)
-- -----------------------------------------------------------------------------
create table if not exists demo.quote_tasks (
  task_did          text primary key,
  org_name          text,
  project_name      text,
  asset_name        text not null,
  -- Slash path ending in a "Mon YYYY" segment; lib/quotes/format.ts siteDate() parses it.
  asset_id          text not null,
  task_name         text not null,
  task_status       text not null default 'Quote Provided',
  subcon            text,
  gc                text,
  carrier           text,
  market            text,
  project           text,
  fuze_id           text,
  needs_review_base boolean not null default false   -- the path could not be parsed cleanly
);

create table if not exists demo.invoice_lines (
  line_key            text primary key,
  task_did            text not null references demo.quote_tasks (task_did) on delete cascade,
  form_did            text,
  project             text,
  site_name           text,
  site_id             text,
  sow                 text,
  pricing_type        text,
  invoice_category    text,
  service_type        text,
  service_type_others text,
  service_rate        text,          -- free text upstream, e.g. "1,250.00"
  ll_cop              text,
  landlord            text,
  landlord_others     text,
  pmi_cop             text,
  rf_mitigation_cop   text,
  requirement_status  text
);
create index if not exists invoice_lines_task_idx on demo.invoice_lines (task_did);

-- -----------------------------------------------------------------------------
-- app_quote working tables
-- -----------------------------------------------------------------------------
-- Per-task manual edits. For the six category fields:
--   NULL = no override (use the parsed value), '' = explicit blank, text = value.
create table if not exists app_quote.overrides (
  task_did                 text primary key,
  subcon                   text,
  gc                       text,
  carrier                  text,
  market                   text,
  project                  text,
  fuze_id                  text,
  verified                 boolean not null default false,
  verified_by              text,
  verified_at              timestamptz,
  chosen_line_key          text,
  service_rate_override    text,
  product_service_override text,
  line_items               jsonb,       -- [{product, qty, rate}] or NULL = single-line quote
  updated_by               text,
  updated_at               timestamptz not null default now()
);

create table if not exists app_quote.generated (
  task_did      text primary key,
  drive_file_id text not null,
  drive_link    text not null,
  generated_by  text not null,
  generated_at  timestamptz not null default now()
);

create table if not exists app_quote.email_queue (
  id               bigint generated by default as identity primary key,
  task_did         text not null,
  sender_email     text not null,
  from_email       text,
  gmail_draft_id   text not null,
  scheduled_at     timestamptz not null,
  status           text not null default 'scheduled'
                   check (status in ('scheduled', 'sent', 'failed', 'cancelled')),
  subject_resolved text not null,
  to_resolved      text not null,
  cc_resolved      text,
  template_name    text,
  created_by       text not null,
  created_at       timestamptz not null default now(),
  sent_at          timestamptz,
  gmail_message_id text,
  error            text,
  claimed_at       timestamptz,
  returned_to      text check (returned_to in ('queue', 'generated')),
  returned_by      text,
  returned_at      timestamptz
);
create index if not exists email_queue_due_idx
  on app_quote.email_queue (scheduled_at) where status = 'scheduled';
create index if not exists email_queue_task_idx on app_quote.email_queue (task_did);

create table if not exists app_quote.email_templates (
  id         bigint generated by default as identity primary key,
  name       text not null unique,
  subject    text not null default '',
  body_html  text not null default '',
  updated_by text,
  updated_at timestamptz not null default now()
);

create table if not exists app_quote.gmail_connections (
  id                bigint generated by default as identity primary key,
  email             text not null,
  refresh_token_enc text not null,     -- AES-256-GCM box, key = GMAIL_TOKEN_KEY
  connected_by      text not null,
  connected_at      timestamptz not null default now(),
  status            text not null default 'active',
  last_error        text,
  unique (connected_by, email)
);

create table if not exists app_quote.user_settings (
  user_email          text primary key,
  active_sender_email text,
  active_from_email   text,
  theme               text,
  swift_username      text,            -- PM API account (internal column name kept)
  swift_password_enc  text,
  swift_verified_at   timestamptz,
  updated_at          timestamptz not null default now()
);

create table if not exists app_quote.send_identities (
  id          bigint generated by default as identity primary key,
  name        text not null,
  email       text not null,
  scope       text not null check (scope in ('shared', 'personal')),
  owner_email text,
  created_by  text not null,
  check ((scope = 'shared' and owner_email is null) or (scope = 'personal' and owner_email is not null))
);
create unique index if not exists send_identities_shared_uq
  on app_quote.send_identities (email) where scope = 'shared';
create unique index if not exists send_identities_personal_uq
  on app_quote.send_identities (owner_email, email) where scope = 'personal';

-- -----------------------------------------------------------------------------
-- RPC: claim due emails exactly once.
-- Stamps claimed_at under FOR UPDATE SKIP LOCKED and returns only the rows THIS
-- call took, so two overlapping dispatcher runs can never send the same draft.
-- status stays 'scheduled' while claimed; the dispatcher then marks each row
-- sent / failed / cancelled, and frees stale claims (claimed_at older than 5 min).
-- -----------------------------------------------------------------------------
create or replace function app_quote.claim_due_emails(p_limit integer default 50)
returns setof app_quote.email_queue
language sql
volatile
set search_path = ''
as $$
  update app_quote.email_queue q
     set claimed_at = now()
   where q.id in (
           select c.id
             from app_quote.email_queue c
            where c.status = 'scheduled'
              and c.returned_at is null
              and c.claimed_at is null
              and c.scheduled_at <= now()
            order by c.scheduled_at, c.id
            limit greatest(coalesce(p_limit, 50), 0)
              for update skip locked
         )
  returning q.*;
$$;

-- -----------------------------------------------------------------------------
-- analytics views (dropped + recreated so column changes always apply)
-- -----------------------------------------------------------------------------
drop view if exists analytics.v_quote_review;
drop view if exists analytics.mv_quote_review;
drop view if exists analytics.mv_quote_invoice_options;
drop view if exists analytics.mv_quote_source_invoice_lines;
drop view if exists analytics.v_quote_source_asset_tasks;
drop view if exists demo.v_invoice_lines_enriched;

-- Helper: invoice lines with the derived product/service label and a numeric rate.
create view demo.v_invoice_lines_enriched with (security_invoker = true) as
select
  l.*,
  coalesce(nullif(btrim(l.invoice_category), ''),
           nullif(btrim(l.service_type), ''),
           nullif(btrim(l.service_type_others), ''))            as product_service,
  case
    when nullif(btrim(l.invoice_category), '') is not null then 'Invoice Category'
    when coalesce(nullif(btrim(l.service_type), ''), nullif(btrim(l.service_type_others), '')) is not null
      then 'Service Type'
  end                                                           as product_service_type,
  coalesce(nullif(regexp_replace(coalesce(l.service_rate, ''), '[^0-9.]', '', 'g'), '')::numeric, 0) as rate_num
from demo.invoice_lines l;

-- Data Source tab: the worklist tasks as parsed from the site path.
create view analytics.v_quote_source_asset_tasks with (security_invoker = true) as
select t.task_did, t.org_name, t.project_name, t.asset_name, t.asset_id, t.task_name,
       t.subcon, t.gc, t.carrier, t.market, t.project, t.fuze_id
from demo.quote_tasks t;

-- Data Source tab: every invoicing-form line for those tasks, priced or not.
create view analytics.mv_quote_source_invoice_lines with (security_invoker = true) as
select l.task_did, t.asset_name, l.project, l.site_name, l.site_id, l.sow, l.pricing_type,
       l.service_type, l.service_type_others, l.service_rate, l.ll_cop, l.landlord,
       l.landlord_others, l.pmi_cop, l.rf_mitigation_cop,
       (l.rate_num > 0) as priced,
       l.form_did
from demo.v_invoice_lines_enriched l
join demo.quote_tasks t using (task_did);

-- Priced lines a user can choose between for a task.
create view analytics.mv_quote_invoice_options with (security_invoker = true) as
select l.task_did, l.line_key, l.product_service, l.product_service_type, l.service_rate,
       l.site_id, l.project, l.requirement_status, l.form_did
from demo.v_invoice_lines_enriched l
where l.rate_num > 0;

-- Base (pre-override) categories; only used for the distinct-value suggestions.
create view analytics.mv_quote_review with (security_invoker = true) as
select t.task_did, t.gc, t.carrier, t.market, t.project
from demo.quote_tasks t;

-- The main read model: one row per task.
create view analytics.v_quote_review with (security_invoker = true) as
with eff as (
  select
    t.task_did, t.asset_id, t.asset_name, t.task_name, t.task_status,
    -- override semantics: NULL = parsed value, '' = explicit blank, text = value
    case when o.subcon  is not null then nullif(o.subcon, '')  else t.subcon  end as subcon,
    case when o.gc      is not null then nullif(o.gc, '')      else t.gc      end as gc,
    case when o.carrier is not null then nullif(o.carrier, '') else t.carrier end as carrier,
    case when o.market  is not null then nullif(o.market, '')  else t.market  end as market,
    case when o.project is not null then nullif(o.project, '') else t.project end as project,
    case when o.fuze_id is not null then nullif(o.fuze_id, '') else t.fuze_id end as fuze_id,
    t.needs_review_base,
    coalesce(o.verified, false)                 as verified,
    o.verified_by, o.verified_at,
    (o.subcon  is not null)                     as subcon_overridden,
    (o.gc      is not null)                     as gc_overridden,
    (o.carrier is not null)                     as carrier_overridden,
    (o.market  is not null)                     as market_overridden,
    (o.project is not null)                     as project_overridden,
    (o.fuze_id is not null)                     as fuze_id_overridden,
    nullif(btrim(o.service_rate_override), '')    as service_rate_override,
    nullif(btrim(o.product_service_override), '') as product_service_override,
    o.chosen_line_key,
    case when jsonb_typeof(o.line_items) = 'array' and jsonb_array_length(o.line_items) > 0
         then o.line_items end                  as line_items,
    o.updated_by                                as override_by,
    o.updated_at                                as override_at
  from demo.quote_tasks t
  left join app_quote.overrides o using (task_did)
),
line_stats as (
  select task_did,
         count(*)                           as line_count,
         count(*) filter (where rate_num > 0) as priced_line_count
  from demo.v_invoice_lines_enriched
  group by task_did
),
picked as (
  -- The user's chosen priced line if it is still valid; otherwise the first
  -- priced line; otherwise the first unpriced line (for site/SOW context).
  select distinct on (e.task_did)
    e.task_did,
    l.line_key, l.project, l.site_name, l.site_id, l.product_service, l.product_service_type,
    l.invoice_category, l.service_type, l.sow, l.service_rate, l.rate_num,
    l.requirement_status, l.form_did,
    (l.line_key = e.chosen_line_key and l.rate_num > 0) as is_chosen
  from eff e
  join demo.v_invoice_lines_enriched l using (task_did)
  order by e.task_did,
           (l.line_key = e.chosen_line_key and l.rate_num > 0) desc,
           (l.rate_num > 0) desc,
           l.line_key
),
dir as (
  select match_key,
         string_agg(distinct nullif(btrim(recipient), ''), ', ') as recipient,
         string_agg(distinct nullif(btrim(cc), ''), ', ')        as cc,
         count(distinct (coalesce(btrim(recipient), '') || '|' || coalesce(btrim(cc), ''))) > 1 as conflict
  from reference.ref_quote_directory
  where match_key is not null
  group by match_key
)
select
  e.task_did, e.asset_id, e.asset_name, e.task_name, e.task_status,
  e.subcon, e.gc, e.carrier, e.market, e.project, e.fuze_id,
  (e.needs_review_base and not e.verified)        as needs_review,
  e.needs_review_base,
  e.verified, e.verified_by, e.verified_at,
  e.subcon_overridden, e.gc_overridden, e.carrier_overridden,
  e.market_overridden, e.project_overridden, e.fuze_id_overridden,
  (e.service_rate_override is not null)           as service_rate_overridden,
  (e.product_service_override is not null)        as product_service_overridden,
  e.override_by, e.override_at,
  p.project                                       as inv_project,
  p.site_name                                     as inv_site_name,
  p.site_id                                       as inv_site_id,
  coalesce(e.product_service_override, p.product_service) as inv_product_service,
  p.product_service_type                          as inv_product_service_type,
  p.invoice_category                              as inv_invoice_category,
  p.service_type                                  as inv_service_type,
  p.sow                                           as inv_sow,
  coalesce(e.service_rate_override,
           case when p.rate_num > 0 then p.service_rate end) as inv_service_rate,
  p.requirement_status                            as inv_requirement_status,
  p.form_did                                      as inv_form_did,
  e.chosen_line_key,
  coalesce(p.is_chosen, false)                    as invoice_chosen,
  d.recipient                                     as quote_recipient,
  d.cc                                            as quote_cc,
  (d.match_key is not null)                       as directory_matched,
  coalesce(d.conflict, false)                     as directory_conflict,
  coalesce(s.priced_line_count, 0)::int           as priced_line_count,
  case
    when coalesce(s.line_count, 0) = 0 then 'no_match'
    when coalesce(p.rate_num, 0) > 0
      or coalesce(nullif(regexp_replace(coalesce(e.service_rate_override, ''), '[^0-9.]', '', 'g'), '')::numeric, 0) > 0
      then 'ready'
    else 'no_price'
  end                                             as status,
  e.line_items
from eff e
left join line_stats s using (task_did)
left join picked p using (task_did)
left join dir d
  on d.match_key =
     upper(regexp_replace(btrim(coalesce(e.gc, '')),      '\s+', ' ', 'g')) || '|' ||
     upper(regexp_replace(btrim(coalesce(e.carrier, '')), '\s+', ' ', 'g')) || '|' ||
     upper(regexp_replace(btrim(coalesce(e.market, '')),  '\s+', ' ', 'g')) || '|' ||
     upper(regexp_replace(btrim(coalesce(e.project, '')), '\s+', ' ', 'g'));

-- -----------------------------------------------------------------------------
-- Row Level Security: on everywhere, no policies. service_role bypasses RLS.
-- -----------------------------------------------------------------------------
alter table reference.ref_quote_directory    enable row level security;
alter table data_staging.stg_invoicing_form  enable row level security;
alter table data_staging.stg_asset_tasks     enable row level security;
alter table demo.quote_tasks                 enable row level security;
alter table demo.invoice_lines               enable row level security;
alter table app_quote.overrides              enable row level security;
alter table app_quote.generated              enable row level security;
alter table app_quote.email_queue            enable row level security;
alter table app_quote.email_templates        enable row level security;
alter table app_quote.gmail_connections      enable row level security;
alter table app_quote.user_settings          enable row level security;
alter table app_quote.send_identities        enable row level security;

-- -----------------------------------------------------------------------------
-- Grants: service_role only. anon / authenticated get nothing.
-- -----------------------------------------------------------------------------
do $$
declare s text;
begin
  foreach s in array array['analytics', 'data_staging', 'reference', 'app_quote', 'demo'] loop
    execute format('revoke all on schema %I from public, anon, authenticated', s);
    execute format('revoke all on all tables in schema %I from public, anon, authenticated', s);
    execute format('revoke all on all functions in schema %I from public, anon, authenticated', s);
    execute format('grant usage on schema %I to service_role', s);
    execute format('grant all on all tables in schema %I to service_role', s);
    execute format('grant all on all sequences in schema %I to service_role', s);
    execute format('grant execute on all functions in schema %I to service_role', s);
    execute format('alter default privileges in schema %I grant all on tables to service_role', s);
    execute format('alter default privileges in schema %I grant all on sequences to service_role', s);
  end loop;
end $$;

-- Ask PostgREST to reload its schema cache (harmless outside Supabase).
notify pgrst, 'reload schema';
